export { TypeTable } from './table.abstract';
export type { ITypeTable } from './table.interface';
export { TypeTableBody } from './body/body.abstract';
export type { ITypeTableBody } from './body/body.interface';
export { TypeTableCaption } from './caption/caption.abstract';
export type { ITypeTableCaption } from './caption/caption.interface';
export { TypeTableCol } from './col/col.abstract';
export type { ITypeTableCol } from './col/col.interface';
export { TypeTableColGroup } from './col-group/col-group.abstract';
export type { ITypeTableColGroup } from './col-group/col-group.interface';
export { TypeTableDataCell } from './data-cell/data-cell.abstract';
export type { ITypeTableDataCell } from './data-cell/data-cell.interface';
export { TypeTableFoot } from './foot/foot.abstract';
export type { ITypeTableFoot } from './foot/foot.interface';
export { TypeTableHead } from './head/head.abstract';
export type { ITypeTableHead } from './head/head.interface';
export { TypeTableHeaderCell } from './header-cell/header-cell.abstract';
export type { ITypeTableHeaderCell } from './header-cell/header-cell.interface';
export { TypeTableRow } from './row/row.abstract';
export type { ITypeTableRow } from './row/row.interface';
