// export { TypeHtml } from './type-html.abstract';
// export type * from './type-html.interface';

export { TypeA } from './a/a.abstract';
export type * from './a/a.interface';
export { TypeAbbr } from './abbr/abbr.abstract';
export type * from './abbr/abbr.interface';
export { TypeAddress } from './address/address.abstract';
export type * from './address/address.interface';
export { TypeArea } from './area/area.abstract';
export type * from './area/area.interface';
export { TypeArticle } from './article/article.abstract';
export type * from './article/article.interface';
export { TypeAside } from './aside/aside.abstract';
export type * from './aside/aside.interface';
export { TypeAudio } from './audio/audio.abstract';
export type * from './audio/audio.interface';
export { TypeB } from './b/b.abstract';
export type * from './b/b.interface';
export { TypeBase } from './base/base.abstract';
export type * from './base/base.interface';
export { TypeBdi } from './bdi/bdi.abstract';
export type * from './bdi/bdi.interface';
export { TypeBdo } from './bdo/bdo.abstract';
export type * from './bdo/bdo.interface';
export { TypeBlockQuote } from './block-quote/block-quote.abstract';
export type * from './block-quote/block-quote.interface';
export { TypeBr } from './br/br.abstract';
export type * from './br/br.interface';
export { TypeButton } from './button/button.abstract';
export type * from './button/button.interface';
export { buttonStyle } from './button/button.const';
export { TypeCanvas } from './canvas/canvas.abstract';
export type * from './canvas/canvas.interface';
export { TypeCite } from './cite/cite.abstract';
export type * from './cite/cite.interface';
export { TypeCode } from './code/code.abstract';
export type * from './code/code.interface';
export { TypeData } from './data/data.abstract';
export type * from './data/data.interface';
export { TypeDataList } from './data-list/data-list.abstract';
export type * from './data-list/data-list.interface';
export { TypeDel } from './del/del.abstract';
export type * from './del/del.interface';
export { TypeDetails } from './details/details.abstract';
export type * from './details/details.interface';
export { TypeDfn } from './dfn/dfn.abstract';
export type * from './dfn/dfn.interface';
export { TypeDialog } from './dialog/dialog.abstract';
export type * from './dialog/dialog.interface';
export { TypeDiv } from './div/div.abstract';
export type * from './div/div.interface';
export { TypeDL } from './dl/dl.abstract';
export type * from './dl/dl.interface';
export { TypeDD } from './dl/dd/dd.abstract';
export type * from './dl/dd/dd.interface';
export { TypeDT } from './dl/dt/dt.abstract';
export type * from './dl/dt/dt.interface';
export { TypeEm } from './em/em.abstract';
export type * from './em/em.interface';
export { TypeEmbed } from './embed/embed.abstract';
export type * from './embed/embed.interface';
export { TypeFieldset } from './fieldset/fieldset.abstract';
export type * from './fieldset/fieldset.interface';
export { TypeFigCaption } from './fig-caption/fig-caption.abstract';
export type * from './fig-caption/fig-caption.interface';
export { TypeFigure } from './figure/figure.abstract';
export type * from './figure/figure.interface';
export { TypeFooter } from './footer/footer.abstract';
export type * from './footer/footer.interface';
export { TypeForm } from './form/form.abstract';
export type * from './form/form.interface';
export { TypeHead } from './head/head.abstract';
export type * from './head/head.interface';
export { TypeHeader } from './header/header.abstract';
export type * from './header/header.interface';
export { TypeHGroup } from './hgroup/hgroup.abstract';
export type * from './hgroup/hgroup.interface';
export { TypeHr } from './hr/hr.abstract';
export type * from './hr/hr.interface';
export { TypeI } from './i/i.abstract';
export type * from './i/i.interface';
export { TypeIFrame } from './iframe/iframe.abstract';
export type * from './iframe/iframe.interface';
export { TypeImg } from './img/img.abstract';
export type * from './img/img.interface';
export { TypeInput } from './input/input.abstract';
export type * from './input/input.interface';
export { TypeIns } from './ins/ins.abstract';
export type * from './ins/ins.interface';
export { TypeKbd } from './kbd/kbd.abstract';
export type * from './kbd/kbd.interface';
export { TypeLabel } from './label/label.abstract';
export type * from './label/label.interface';
export { TypeLegend } from './legend/legend.abstract';
export type * from './legend/legend.interface';
export { TypeMain } from './main/main.abstract';
export type * from './main/main.interface';
export { TypeMap } from './map/map.abstract';
export type * from './map/map.interface';
export { TypeMark } from './mark/mark.abstract';
export type * from './mark/mark.interface';
export { TypeMenu } from './menu/menu.abstract';
export type * from './menu/menu.interface';
export { TypeMenuItem } from './menu-item/menu-item.abstract';
export type * from './menu-item/menu-item.interface';
export { TypeMeter } from './meter/meter.abstract';
export type * from './meter/meter.interface';
export { TypeNav } from './nav/nav.abstract';
export type * from './nav/nav.interface';
export { TypeOL } from './ol/ol.abstract';
export type * from './ol/ol.interface';
export { TypeOptGroup } from './opt-group/opt-group.abstract';
export type * from './opt-group/opt-group.interface';
export { TypeOption } from './option/option.abstract';
export type * from './option/option.interface';
export { TypeOutput } from './output/output.abstract';
export type * from './output/output.interface';
export { TypeP } from './p/p.abstract';
export type * from './p/p.interface';
export { TypePicture } from './picture/picture.abstract';
export type * from './picture/picture.interface';
export { TypePre } from './pre/pre.abstract';
export type * from './pre/pre.interface';
export { TypeProgress } from './progress/progress.abstract';
export type * from './progress/progress.interface';
export { TypeQ } from './q/q.abstract';
export type * from './q/q.interface';
export { TypeRp } from './rp/rp.abstract';
export type * from './rp/rp.interface';
export { TypeRt } from './rt/rt.abstract';
export type * from './rt/rt.interface';
export { TypeRuby } from './ruby/ruby.abstract';
export type * from './ruby/ruby.interface';
export { TypeS } from './s/s.abstract';
export type * from './s/s.interface';
export { TypeSamp } from './samp/samp.abstract';
export type * from './samp/samp.interface';
export { TypeSection } from './section/section.abstract';
export type * from './section/section.interface';
export { TypeSelect } from './select/select.abstract';
export type * from './select/select.interface';
export { TypeSlot } from './slot/slot.abstract';
export type * from './slot/slot.interface';
export { TypeSmall } from './small/small.abstract';
export type * from './small/small.interface';
export { TypeSource } from './source/source.abstract';
export type * from './source/source.interface';
export { TypeSpan } from './span/span.abstract';
export type * from './span/span.interface';
export { TypeStrong } from './strong/strong.abstract';
export type * from './strong/strong.interface';
export { TypeSub } from './sub/sub.abstract';
export type * from './sub/sub.interface';
export * from './table';
export { TypeTextarea } from './textarea/textarea.abstract';
export type * from './textarea/textarea.interface';
export { TypeTemplate } from './template/template.abstract';
export type * from './template/template.interface';
export { TypeTime } from './time/time.abstract';
export type * from './time/time.interface';
export { TypeTitle } from './title/title.abstract';
export type * from './title/title.interface';
export { TypeTrack } from './track/track.abstract';
export type * from './track/track.interface';
export { TypeU } from './u/u.abstract';
export type * from './u/u.interface';
export { TypeUL } from './ul/ul.abstract';
export type * from './ul/ul.interface';
export { TypeLI } from './li/li.abstract';
export type * from './li/li.interface';
export { TypeVar } from './var/var.abstract';
export type * from './var/var.interface';
export { TypeVideo } from './video/video.abstract';
export type * from './video/video.interface';
export { TypeWbr } from './wbr/wbr.abstract';
export type * from './wbr/wbr.interface';
