export { TypeTable } from './table.abstract';
export type * from './table.interface';
export { TypeTableBody, TypeTableBody as TypeTBody } from './body/body.abstract';
export type * from './body/body.interface';
export { TypeTableCaption, TypeTableCaption as TypeCaption } from './caption/caption.abstract';
export type * from './caption/caption.interface';
export { TypeTableCol, TypeTableCol as TypeTCol } from './col/col.abstract';
export type * from './col/col.interface';
export { TypeTableColGroup, TypeTableColGroup as TypeColGroup } from './col-group/col-group.abstract';
export type * from './col-group/col-group.interface';
export { TypeTableDataCell, TypeTableDataCell as TypeTd } from './data-cell/data-cell.abstract';
export type * from './data-cell/data-cell.interface';
export { TypeTableFoot, TypeTableFoot as TypeTFoot } from './foot/foot.abstract';
export type * from './foot/foot.interface';
export { TypeTableHead, TypeTableHead as TypeTHead } from './head/head.abstract';
export type * from './head/head.interface';
export { TypeTableHeaderCell, TypeTableHeaderCell as TypeTh } from './header-cell/header-cell.abstract';
export type * from './header-cell/header-cell.interface';
export { TypeTableRow, TypeTableRow as TypeTr } from './row/row.abstract';
export type * from './row/row.interface';
