export { TypeA } from './a/a.abstract';
export type { ITypeA } from './a/a.interface';
export { TypeAbbr } from './abbr/abbr.abstract';
export type { ITypeAbbr } from './abbr/abbr.interface';
export { TypeAddress } from './address/address.abstract';
export type { ITypeAddress } from './address/address.interface';
export { TypeArea } from './area/area.abstract';
export type { ITypeArea } from './area/area.interface';
export { TypeArticle } from './article/article.abstract';
export type { ITypeArticle } from './article/article.interface';
export { TypeAside } from './aside/aside.abstract';
export type { ITypeAside } from './aside/aside.interface';
export { TypeAudio } from './audio/audio.abstract';
export type { ITypeAudio } from './audio/audio.interface';
export { TypeB } from './b/b.abstract';
export type { ITypeB } from './b/b.interface';
export { TypeBase } from './base/base.abstract';
export type { ITypeBase } from './base/base.interface';
export { TypeBdi } from './bdi/bdi.abstract';
export type { ITypeBdi } from './bdi/bdi.interface';
export { TypeBdo } from './bdo/bdo.abstract';
export type { ITypeBdo } from './bdo/bdo.interface';
export { TypeBlockQuote } from './block-quote/block-quote.abstract';
export type { ITypeBlockQuote } from './block-quote/block-quote.interface';
export { TypeBr } from './br/br.abstract';
export type { ITypeBr } from './br/br.interface';
export { TypeButton } from './button/button.abstract';
export type { ITypeButton } from './button/button.interface';
export { buttonStyle } from './button/button.const';
export { TypeCanvas } from './canvas/canvas.abstract';
export type { ITypeCanvas } from './canvas/canvas.interface';
export { TypeCite } from './cite/cite.abstract';
export type { ITypeCite } from './cite/cite.interface';
export { TypeCode } from './code/code.abstract';
export type { ITypeCode } from './code/code.interface';
export { TypeData } from './data/data.abstract';
export type { ITypeData } from './data/data.interface';
export { TypeDataList } from './data-list/data-list.abstract';
export type { ITypeDataList } from './data-list/data-list.interface';
export { TypeDel } from './del/del.abstract';
export type { ITypeDel } from './del/del.interface';
export { TypeDetails } from './details/details.abstract';
export type { ITypeDetails } from './details/details.interface';
export { TypeDfn } from './dfn/dfn.abstract';
export type { ITypeDfn } from './dfn/dfn.interface';
export { TypeDialog } from './dialog/dialog.abstract';
export type { ITypeDialog } from './dialog/dialog.interface';
export { TypeDiv } from './div/div.abstract';
export type { ITypeDiv } from './div/div.interface';
export { TypeDL } from './dl/dl.abstract';
export type { ITypeDL } from './dl/dl.interface';
export { TypeDD } from './dl/dd/dd.abstract';
export type { ITypeDD } from './dl/dd/dd.interface';
export { TypeDT } from './dl/dt/dt.abstract';
export type { ITypeDT } from './dl/dt/dt.interface';
export { TypeEm } from './em/em.abstract';
export type { ITypeEm } from './em/em.interface';
export { TypeEmbed } from './embed/embed.abstract';
export type { ITypeEmbed } from './embed/embed.interface';
export { TypeFieldset } from './fieldset/fieldset.abstract';
export type { ITypeFieldset } from './fieldset/fieldset.interface';
export { TypeFigCaption } from './fig-caption/fig-caption.abstract';
export type { ITypeFigCaption } from './fig-caption/fig-caption.interface';
export { TypeFigure } from './figure/figure.abstract';
export type { ITypeFigure } from './figure/figure.interface';
export { TypeFooter } from './footer/footer.abstract';
export type { ITypeFooter } from './footer/footer.interface';
export { TypeForm } from './form/form.abstract';
export type { ITypeForm } from './form/form.interface';
export { TypeHead } from './head/head.abstract';
export type { ITypeHead } from './head/head.interface';
export { TypeHeader } from './header/header.abstract';
export type { ITypeHeader } from './header/header.interface';
export { TypeHGroup } from './hgroup/hgroup.abstract';
export type { ITypeHGroup } from './hgroup/hgroup.interface';
export { TypeHr } from './hr/hr.abstract';
export type { ITypeHr } from './hr/hr.interface';
export { TypeI } from './i/i.abstract';
export type { ITypeI } from './i/i.interface';
export { TypeIFrame } from './iframe/iframe.abstract';
export type { ITypeIFrame } from './iframe/iframe.interface';
export { TypeImg } from './img/img.abstract';
export type { ITypeImg } from './img/img.interface';
export { TypeInput } from './input/input.abstract';
export type { ITypeInput } from './input/input.interface';
export { TypeIns } from './ins/ins.abstract';
export type { ITypeIns } from './ins/ins.interface';
export { TypeKbd } from './kbd/kbd.abstract';
export type { ITypeKbd } from './kbd/kbd.interface';
export { TypeLabel } from './label/label.abstract';
export type { ITypeLabel } from './label/label.interface';
export { TypeLegend } from './legend/legend.abstract';
export type { ITypeLegend } from './legend/legend.interface';
export { TypeMain } from './main/main.abstract';
export type { ITypeMain } from './main/main.interface';
export { TypeMap } from './map/map.abstract';
export type { ITypeMap } from './map/map.interface';
export { TypeMark } from './mark/mark.abstract';
export type { ITypeMark } from './mark/mark.interface';
export { TypeMenu } from './menu/menu.abstract';
export type { ITypeMenu } from './menu/menu.interface';
export { TypeMenuItem } from './menu-item/menu-item.abstract';
export type { ITypeMenuItem } from './menu-item/menu-item.interface';
export { TypeMeter } from './meter/meter.abstract';
export type { ITypeMeter } from './meter/meter.interface';
export { TypeNav } from './nav/nav.abstract';
export type { ITypeNav } from './nav/nav.interface';
export { TypeOL } from './ol/ol.abstract';
export type { ITypeOL } from './ol/ol.interface';
export { TypeOptGroup } from './opt-group/opt-group.abstract';
export type { ITypeOptGroup } from './opt-group/opt-group.interface';
export { TypeOption } from './option/option.abstract';
export type { ITypeOption } from './option/option.interface';
export { TypeOutput } from './output/output.abstract';
export type { ITypeOutput } from './output/output.interface';
export { TypeP } from './p/p.abstract';
export type { ITypeP } from './p/p.interface';
export { TypePicture } from './picture/picture.abstract';
export type { ITypePicture } from './picture/picture.interface';
export { TypePre } from './pre/pre.abstract';
export type { ITypePre } from './pre/pre.interface';
export { TypeProgress } from './progress/progress.abstract';
export type { ITypeProgress } from './progress/progress.interface';
export { TypeQ } from './q/q.abstract';
export type { ITypeQ } from './q/q.interface';
export { TypeRp } from './rp/rp.abstract';
export type { ITypeRp } from './rp/rp.interface';
export { TypeRt } from './rt/rt.abstract';
export type { ITypeRt } from './rt/rt.interface';
export { TypeRuby } from './ruby/ruby.abstract';
export type { ITypeRuby } from './ruby/ruby.interface';
export { TypeS } from './s/s.abstract';
export type { ITypeS } from './s/s.interface';
export { TypeSamp } from './samp/samp.abstract';
export type { ITypeSamp } from './samp/samp.interface';
export { TypeSection } from './section/section.abstract';
export type { ITypeSection } from './section/section.interface';
export { TypeSelect } from './select/select.abstract';
export type { ITypeSelect } from './select/select.interface';
export { TypeSlot } from './slot/slot.abstract';
export type { ITypeSlot } from './slot/slot.interface';
export { TypeSmall } from './small/small.abstract';
export type { ITypeSmall } from './small/small.interface';
export { TypeSource } from './source/source.abstract';
export type { ITypeSource } from './source/source.interface';
export { TypeSpan } from './span/span.abstract';
export type { ITypeSpan } from './span/span.interface';
export { TypeStrong } from './strong/strong.abstract';
export type { ITypeStrong } from './strong/strong.interface';
export { TypeSub } from './sub/sub.abstract';
export type { ITypeSub } from './sub/sub.interface';
export * from './table';
export { TypeTextarea } from './textarea/textarea.abstract';
export type { ITypeTextarea } from './textarea/textarea.interface';
export { TypeTemplate } from './template/template.abstract';
export type { ITypeTemplate } from './template/template.interface';
export { TypeTime } from './time/time.abstract';
export type { ITypeTime } from './time/time.interface';
export { TypeTitle } from './title/title.abstract';
export type { ITypeTitle } from './title/title.interface';
export { TypeTrack } from './track/track.abstract';
export type { ITypeTrack } from './track/track.interface';
export { TypeU } from './u/u.abstract';
export type { ITypeU } from './u/u.interface';
export { TypeUL } from './ul/ul.abstract';
export type { ITypeUL } from './ul/ul.interface';
export { TypeLI } from './ul/li/li.abstract';
export type { ITypeLI } from './ul/li/li.interface';
export { TypeVar } from './var/var.abstract';
export type { ITypeVar } from './var/var.interface';
export { TypeVideo } from './video/video.abstract';
export type { ITypeVideo } from './video/video.interface';
export { TypeWbr } from './wbr/wbr.abstract';
export type { ITypeWbr } from './wbr/wbr.interface';
