export { TableRow, TableRow as Tr } from './row/row.class';
export type { ITableRow } from './row/row.interface';
export { TableDataCell, TableDataCell as Td } from './data-cell/data-cell.class';
export type { ITableDataCell } from './data-cell/data-cell.interface';
export { TableBody, TableBody as Tbody } from './body/body.class';
export type { ITableBody } from './body/body.interface';
export { TableCaption, TableCaption as Caption } from './caption/caption.class';
export type { ITableCaption } from './caption/caption.interface';
export { TableCol, TableCol as Col } from './col/col.class';
export type { ITableCol } from './col/col.interface';
export { TableColGroup, TableColGroup as ColGroup } from './col-group/col-group.class';
export type { ITableColGroup } from './col-group/col-group.interface';
export { TableFoot, TableFoot as TFoot } from './foot/foot.class';
export type { ITableFoot } from './foot/foot.interface';
export { TableHead, TableHead as Thead } from './head/head.class';
export type { ITableHead } from './head/head.interface';
export { TableHeaderCell, TableHeaderCell as Th } from './header-cell/header-cell.class';
export type { ITableHeaderCell } from './header-cell/header-cell.interface';
export { Table } from './table.class';
export type { ITable } from './table.interface';
